beer_collector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # All the paths to create, update delete beers
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('beers/', views.beers_index, name='index'),
    path('beers/<int:beer_id>/', views.beers_detail, name='detail'),
    path('beers/create', views.BeerCreate.as_view(), name='beers_create'),
    path('beers/<int:pk>/update/', views.BeerUpdate.as_view(), name='beers_update'),
    path('beers/<int:pk>/delete/', views.BeerDelete.as_view(), name='beers_delete'),
   
    # Path to add a drinking schedule to a beer beer    
    path('beers/<int:beer_id>/add_drinking', views.add_drinking, name='add_drinking'),

    # path for adding photo
    path('beers/<int:beer_id>/add_photo', views.add_photo, name='add_photo'),

    # paths to create, update, delete awards   
    path('awards/', views.AwardList.as_view(), name='awards_index'),
    path('awards/<int:pk>/', views.AwardDetail.as_view(), name='awards_detail'),
    path('awards/create/', views.AwardCreate.as_view(), name='awards_create'),
    path('awards/<int:pk>/update', views.AwardUpdate.as_view(), name='awards_update'),
    path('awards/<int:pk>/delete', views.AwardDelete.as_view(), name='awards_delete'),

    # Associate and Unassociate the award with the beer 
    path('beers/<int:beer_id>/assoc_award/<int:award_id>/', views.assoc_award, name='assoc_award'),
    path('beers/<int:beer_id>/unassoc_award/<int:award_id>/', views.unassoc_award, name='unassoc_award')
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date


DRINKS = (
    ('M', 'Morning Drink'),
    ('A', 'Afternoon Drink'),
    ('N', 'Night Drink')
)

class Award(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('awards_detail', kwargs={'pk': self.id})

# Create your models here.
class Beer(models.Model):
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    alcPercent = models.CharField(max_length=10)
    abuLevel = models.IntegerField()
    origin = models.CharField(max_length=30)
    awards = models.ManyToManyField(Award)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'beer_id': self.id})
    
    def drunk_for_today(self):
        return self.drinking_set.filter(date=date.today()).count() >= len(DRINKS)
    

class Photo(models.Model):
    url = models.CharField(max_length=200)
    beer = models.ForeignKey(Beer, on_delete=models.CASCADE)

    def __str__(self):
        return f'Photo for beer_id: {self.beer_id} @{self.url}'

class Drinking(models.Model):
    date = models.DateField('drinking date')
    drink = models.CharField(
        max_length=1,
        choices=DRINKS,
        # default sets the defauly value to the first one, which is M in DRINKS
        default=DRINKS[0][0]
    )

    beer = models.ForeignKey(Beer, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f'{self.get_drink_display()} on {self.date}'

main_app/forms.py
from django.forms import ModelForm
from .models import Drinking

class DrinkingForm(ModelForm):
    class Meta:
        model = Drinking
        fields = ['date', 'drink']

main_app/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.shortcuts import redirect, render
from .models import Beer, Award, Photo
from main_app import models
from .forms import DrinkingForm
import boto3
import uuid

S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com'
BUCKET = 'beer-collector-swaroop'

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def beers_index(request):
    beers = Beer.objects.all(); 
    return render(request, 'beers/index.html', {'beers': beers})

def beers_detail(request, beer_id):
    beer = Beer.objects.get(id=beer_id)
    awards_beer_doesnt_have = Award.objects.exclude(id__in = beer.awards.all().values_list('id'))
    # instantiate the Drinking Form
    drinking_form = DrinkingForm()
    return render(request, 'beers/detail.html', {
        'beer': beer,
        'drinking_form': drinking_form,
        'awards': awards_beer_doesnt_have
    })

def add_drinking(request, beer_id):
    # Create the model form using the data in the request.POST
    form = DrinkingForm(request.POST)
    # validate the form
    if form.is_valid():
        # don't save the form to the db until it has the beer_id assigned.
        # commit=False means we save it in memory, without actually storing in the db
        new_drinking = form.save(commit=False)
        new_drinking.beer_id = beer_id
        new_drinking.save()
    return redirect('detail', beer_id=beer_id)


def add_photo(request, beer_id):
    # photo-file will be the 'name' attribute on the <input type='file'>
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # the following key is to generate a unique key for s3, that will be appended to each img url
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            # build out the fill url string
            url = f'{S3_BASE_URL}/{BUCKET}/{key}'
            # assign photo to a beer_id or beer and save it to db
            photo = Photo(url=url, beer_id=beer_id)
            photo.save()
        except Exception as error:
            print('An error has occurred while uploading the file to S3');
            print(error)
    return redirect('detail', beer_id=beer_id)

def assoc_award(request, beer_id, award_id):
    Beer.objects.get(id=beer_id).awards.add(award_id)
    return redirect('detail', beer_id=beer_id)

def unassoc_award(request, beer_id, award_id):
    Beer.objects.get(id=beer_id).awards.remove(award_id)
    return redirect('detail', beer_id=beer_id)

class BeerCreate(CreateView):
    model = Beer
    fields = ['name', 'type', 'alcPercent', 'abuLevel', 'origin']

class BeerUpdate(UpdateView):
    model = Beer
    fields = ['type', 'alcPercent', 'abuLevel', 'origin']

class BeerDelete(DeleteView):
    model = Beer
    success_url = '/beers/'

class AwardList(ListView):
  model = Award

class AwardDetail(DetailView):
  model = Award

class AwardCreate(CreateView):
  model = Award
  fields = '__all__'

class AwardUpdate(UpdateView):
  model = Award
  fields = ['name', 'color']

class AwardDelete(DeleteView):
  model = Award
  success_url = '/awards/'

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}
    <h1>About Beer Collector</h1>
    <hr />
    <p>We collect Beers</p>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <title>Beer Collector</title>
</head>
<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <li>
                        <a class='left brand-logo'href="{% url 'home' %}">Beer Collector</a>
                    </li>
                </ul>
                <ul class='right'>
                    <li>
                        <a href="{% url 'about' %}">About</a>
                    </li>
                    <li>
                        <a href="{% url 'awards_create' %}">Add an Award</a>
                    </li>
                    <li>
                        <a href="{% url 'awards_index' %}">View all Awards</a>
                    </li>
                    <li>
                        <a href="{% url 'index' %}">Beers</a>
                    </li>
                    <li>
                        <a href="{% url 'beers_create' %}">Add a Beer</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="page-footer">
        <div class="right">All Rights Reserverd, &copy; 2021 Beer Collector</div>
    </footer>
    
    
</body>
</html>

main_app/templates/beers/detail.html
{% extends 'base.html' %}

{% block content %}
<h1>Beer Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ beer.name }}</span>
        <p>Type: {{ beer.type }}</p>
        <p>Origin: {{ beer.origin }}</p>
        <p>Alcohol Percent: {{ beer.alcPercent }}</p>
        {% if beer.abuLevel > 7  %}
        <p>Bitterness Level: High</p>
        {% elif 3 <= beer.abuLevel <= 7 %}
        <p>Bitterness Level: Medium</p>
        {% else %}
        <p>Bitterness Level: Low</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'beers_update' beer.id %}">Edit</a>
        <a href="{% url 'beers_delete' beer.id %}">Delete</a>
      </div>
    </div>

    {% for photo in beer.photo_set.all %}
    <img src="{{ photo.url }}" alt="" class="responsive-img card-panel">
    {% empty %}
    <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}

        <form action="{% url 'add_photo' beer.id %}" method="POST" enctype="multipart/form-data" class="card-panel">
          {% csrf_token %}
          <input type="file" name='photo-file'>
          <br>
          <br>
          <input type="submit" class="btn" value="Upload Photo">
        </form>
  </div>

  <div class="col s6">
    <form action="{% url 'add_drinking' beer.id %}" method="post">
      {% csrf_token %}
      {{ drinking_form.as_p }}
      <input type="submit" class="btn" value="Add drinking">
    </form>
    <br>
    {% if beer.drunk_for_today %}
    <div class="card-panel teal-text center-align">You've drunk enough {{beer.name}} for today. CHILL OUT!</div>
    {% else %}
    <div class="card-panel red-text center-align">Drink more {{beer.name}}. BOTTOMS UP!!</div>
    {% endif %}
    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Drink</th>
        </tr>
      </thead>
      <tbody>
        {% for drinking in beer.drinking_set.all %}
        <tr>
          <td>{{drinking.date}}</td>
          <td>{{drinking.get_drink_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ beer.name }}'s awards</h3>
    {% if beer.awards.count %}
    {% for award in beer.awards.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">A<span style="color: {{ award.color }}"> {{ award.color }}</span>
          {{ award.name }}</span>
      </div>
      <div class="card-action">
        <form action="{% url 'unassoc_award' beer.id award.id %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn">Remove</button>
        </form>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <h5>No awards :(</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available awards</h3>
    {% if awards.count %}
    {% for award in awards.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          A <span style="color: {{ award.color }}">{{ award.color }}</span> {{ award.name }}
        </span>
      </div>
      <div class="card-action">
        <form action="{% url 'assoc_award' beer.id award.id %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn">Add</button>
        </form>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <h5>{{beer.name}} Already Has All awards Available</h5>
    {% endif %}
  </div>
</div>



<script>
  // Elements
  let dateEl = document.querySelector('#id_date');
  let selectEl = document.querySelector('#id_drink');

  // Initialize the date field with datepicker
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  // Initialize the select field 
  M.FormSelect.init(selectEl)
</script>
{% endblock %}

main_app/templates/beers/index.html
{% extends 'base.html' %}

{% block content %}
<h1>List of Beers</h1>
{% for beer in beers %}
    <div class="card">
        <a href='/beers/{{ beer.id }}'>
            <div class="card-content">
                <span class="card-title">{{ beer.name }}</span>
                <p><span class="column">Type: </span> {{ beer.type }}</p>
                <p><span class="column">Origin: </span>{{ beer.origin }}</p>
                <p><span class="column">Alcohol Percent: </span> {{ beer.alcPercent }}</p>
                {% if beer.abuLevel > 6 %}
                <p><span class="column">Bitterness: </span>High</p>
                {% else %}
                <p><span class="column">Bitterness: </span>Low</p>
                {% endif %}
            </div>
        </a>
    </div>
{% endfor %}
{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <h1>Welcome to the Beer Collector</h1>
    <hr />
    <p>We collect beers from all over the world</p>
{% endblock %}

main_app/templates/main_app/award_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Award</h1>

<h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="YES! - Delete" class="btn">
    <a href="{% url 'awards_delete' object.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/award_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>Award Details</h1>

    <div class="row">
        <div class="col s6 col-offset-3">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">{{ award.name }}</span>
                    <p>Color: {{ award.color }}</p>
                </div>
                <div class="card-action">
                    <a href="{% url 'awards_update' award.id %}">Edit</a>
                    <a href="{% url 'awards_delete' award.id %}">Delete</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

main_app/templates/main_app/award_form.html
{% extends 'base.html' %}

{% block content %}
    {%  if object %}
    <h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
    {%  else %}
    <h1>Add an Award</h1>
    {%  endif %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="submit" class="btn">
    </form>
{% endblock %}

main_app/templates/main_app/award_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Awards List</h1>

{% for award in award_list %}
    <a href="{% url 'awards_detail' award.id %}">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ award.name }}</span>
                <p>Color: {{ award.color }}</p>
            </div>
        </div>
    </a>

{% endfor %}
{% endblock %}

main_app/templates/main_app/beer_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Delete Beer</h1>

<h4>Are you sure you want to delete <span class='teal-text'>{{ object.name }}</span></h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" class="btn" value="Yes - Delete!">
    <a href="{% url 'detail' object.id %}"></a>
</form>

{% endblock %}

main_app/templates/main_app/beer_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <h1>Edit <span class="teal-text">{{ object.name }}</span></h1>
{% else %}
    <h1>Add a Beer</h1>
{% endif %}

<form action="" method='POST'>
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" class="btn" name="submit">
</form>


{% endblock %}